/**
 * This file was automatically generated. DO NOT MODIFY.
 */

import { PipelineSchemaBuilderModel } from "../../../serafin/pipeline";

/**
 * Schema of an item category.
 */
export interface Category {
  id: string;
  name: string;
  parentCategory?: string;
}
/**
 * This interface was referenced by `Category`'s JSON-Schema
 * via the `definition` "createValues".
 */
export interface CreateValues {
  id?: string;
  name: string;
  parentCategory?: string;
}
/**
 * This interface was referenced by `Category`'s JSON-Schema
 * via the `definition` "updateValues".
 */
export interface UpdateValues {
  id?: string;
  name: string;
  parentCategory?: string;
}
/**
 * This interface was referenced by `Category`'s JSON-Schema
 * via the `definition` "readQuery".
 */
export interface ReadQuery {
  /**
   * Category identifier. It is generated by the API.
   */
  id?: string | string[];
  /**
   * Category name
   */
  name?: string | string[];
  parentCategory?: string | string[];
}
/**
 * This interface was referenced by `Category`'s JSON-Schema
 * via the `definition` "patchQuery".
 */
export interface PatchQuery {
  id: string | string[];
  name?: string | string[];
  parentCategory?: string | string[];
}
/**
 * This interface was referenced by `Category`'s JSON-Schema
 * via the `definition` "patchValues".
 */
export interface PatchValues {
  name?: string;
  parentCategory?: string;
}
/**
 * This interface was referenced by `Category`'s JSON-Schema
 * via the `definition` "deleteQuery".
 */
export interface DeleteQuery {
  id: string | string[];
}


export var categorySchema = new PipelineSchemaBuilderModel<Category, ReadQuery, CreateValues, UpdateValues, PatchQuery, PatchValues, DeleteQuery>({"type":"object","title":"Category","description":"Schema of an item category.","properties":{"id":{"type":"string"},"name":{"type":"string"},"parentCategory":{"type":"string"}},"required":["id","name"],"additionalProperties":false,"definitions":{"createValues":{"type":"object","properties":{"id":{"type":"string"},"name":{"type":"string"},"parentCategory":{"type":"string"}},"additionalProperties":false,"required":["name"]},"updateValues":{"type":"object","properties":{"id":{"type":"string"},"name":{"type":"string"},"parentCategory":{"type":"string"}},"additionalProperties":false,"required":["name"]},"readQuery":{"type":"object","properties":{"id":{"oneOf":[{"type":"string"},{"type":"array","items":{"type":"string"}}],"description":"Category identifier. It is generated by the API."},"name":{"oneOf":[{"type":"string"},{"type":"array","items":{"type":"string"}}],"description":"Category name"},"parentCategory":{"oneOf":[{"type":"string"},{"type":"array","items":{"type":"string"}}]}},"additionalProperties":false},"patchQuery":{"type":"object","properties":{"id":{"oneOf":[{"type":"string"},{"type":"array","items":{"type":"string"}}]},"name":{"oneOf":[{"type":"string"},{"type":"array","items":{"type":"string"}}]},"parentCategory":{"oneOf":[{"type":"string"},{"type":"array","items":{"type":"string"}}]}},"additionalProperties":false,"required":["id"]},"patchValues":{"type":"object","properties":{"name":{"type":"string"},"parentCategory":{"type":"string"}},"additionalProperties":false},"deleteQuery":{"type":"object","properties":{"id":{"oneOf":[{"type":"string"},{"type":"array","items":{"type":"string"}}]}},"additionalProperties":false,"required":["id"]}}}, "Category");
