/**
 * This file was automatically generated. DO NOT MODIFY.
 */

import { PipelineSchemaBuilderModel } from "../../../serafin/pipeline";

/**
 * Schema of a Pet object.
 */
export interface Item {
  id: string;
  name: string;
}

export interface CreateValues {
  id?: string;
  name: string;
}

export interface UpdateValues {
  id?: string;
  name: string;
}

export interface ReadQuery {
  /**
   * The identifier of the Pet. It is generated by the API.
   */
  id?: (string | string[]);
  /**
   * Item name
   */
  name?: (string | string[]);
}

export interface PatchQuery {
  id: (string | string[]);
  name?: (string | string[]);
}

export interface PatchValues {
  name?: string;
}

export interface DeleteQuery {
  id: (string | string[]);
}


export var itemSchema = new PipelineSchemaBuilderModel<Item, ReadQuery, CreateValues, UpdateValues, PatchQuery, PatchValues, DeleteQuery>({"type":"object","title":"Item","description":"Schema of a Pet object.","properties":{"id":{"type":"string"},"name":{"type":"string"}},"required":["id","name"],"additionalProperties":false,"definitions":{"createValues":{"type":"object","properties":{"id":{"type":"string"},"name":{"type":"string"}},"additionalProperties":false,"required":["name"]},"updateValues":{"type":"object","properties":{"id":{"type":"string"},"name":{"type":"string"}},"additionalProperties":false,"required":["name"]},"readQuery":{"type":"object","properties":{"id":{"oneOf":[{"type":"string"},{"type":"array","items":{"type":"string"}}],"description":"The identifier of the Pet. It is generated by the API."},"name":{"oneOf":[{"type":"string"},{"type":"array","items":{"type":"string"}}],"description":"Item name"}},"additionalProperties":false},"patchQuery":{"type":"object","properties":{"id":{"oneOf":[{"type":"string"},{"type":"array","items":{"type":"string"}}]},"name":{"oneOf":[{"type":"string"},{"type":"array","items":{"type":"string"}}]}},"additionalProperties":false,"required":["id"]},"patchValues":{"type":"object","properties":{"name":{"type":"string"}},"additionalProperties":false},"deleteQuery":{"type":"object","properties":{"id":{"oneOf":[{"type":"string"},{"type":"array","items":{"type":"string"}}]}},"additionalProperties":false,"required":["id"]}}}, "Item");
