import { SchemaBuilder } from "@serafin/schema-builder"

export var petSchemaBuilder = SchemaBuilder.emptySchema()
  .addString("id", { description: "The identifier of the Pet. It is generated by the API." })
  .addString("name", { description: "The name of the Pet. If not provided the API generate one automatically.", examples: ["Snowball"] })
  .addEnum("category", ["cat", "dog", "tiger"], { description: "The category of the pet." })
  .addArray("tags", SchemaBuilder.stringSchema(), { description: "A list of tags to ease classification." }, false)
  .addArray("photoUrls", SchemaBuilder.stringSchema(), { description: "Urls to photos of this Pet." }, false)
